version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - uploads:/app/uploads

  frontend:
    build: ./frontend
    ports:
      - "8081:3000"

volumes:
  uploads:
